package startup;

import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (10/24/2018, 11:35) **/
public class ClientNodeSpringStartup {
    /**
     * Start up node with specified configuration.
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        Ignition.start("ImportedCluster-client.xml");
    }
}